// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrOEt9JkEDpVqBHVr3XO45ny2A-Kq1SwQ',
    appId: '1:493993942830:web:7aad9011cbc760b04364bf',
    messagingSenderId: '493993942830',
    projectId: 'moonup-919b1',
    authDomain: 'moonup-919b1.firebaseapp.com',
    storageBucket: 'moonup-919b1.firebasestorage.app',
    measurementId: 'G-4D5BQBHJ0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgAQSubUDKsA_M8pAb2z8RMGKTYCTfT0E',
    appId: '1:493993942830:android:f540dcbba422ac934364bf',
    messagingSenderId: '493993942830',
    projectId: 'moonup-919b1',
    storageBucket: 'moonup-919b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvIUeXDFcKckPsrd3uv6GDO2w7NQtNc5A',
    appId: '1:493993942830:ios:ad9db5c71e9126054364bf',
    messagingSenderId: '493993942830',
    projectId: 'moonup-919b1',
    storageBucket: 'moonup-919b1.firebasestorage.app',
    iosBundleId: 'com.danielcordoba.moonUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvIUeXDFcKckPsrd3uv6GDO2w7NQtNc5A',
    appId: '1:493993942830:ios:f2ace458627b9cf54364bf',
    messagingSenderId: '493993942830',
    projectId: 'moonup-919b1',
    storageBucket: 'moonup-919b1.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrOEt9JkEDpVqBHVr3XO45ny2A-Kq1SwQ',
    appId: '1:493993942830:web:998d991038f00dbe4364bf',
    messagingSenderId: '493993942830',
    projectId: 'moonup-919b1',
    authDomain: 'moonup-919b1.firebaseapp.com',
    storageBucket: 'moonup-919b1.firebasestorage.app',
    measurementId: 'G-VYTWLJ6DN8',
  );
}
